config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users
  resources :products do
    resources :comments
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get '/products', to: 'products#index'

  get 'static_pages/index'

  root 'static_pages#landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders, only: [:index, :show, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Jim Whites</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%=csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%=stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%=javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top " role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand">
          <%=image_tag( "jim-whites-logo-.png", class: "img-fluid") %>
        </a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li>
            <%=link_to "Home", root_path %>
          </li>
          <li>
            <%=link_to "Search Autos", products_path %>
          </li>
          <li>
            <%=link_to "About Us", static_pages_about_path %>
          </li>
          <li>
            <%=link_to "Contact", static_pages_contact_path %>
          </li>
        </ul>
        <div class="form-group">
          <%=form_tag( "/products", method: "get", class: "navbar-form navbar-right") do %>   
            <%= text_field_tag(:q, "", type:"text", class:"form-control", placeholder:"Search...") %> 
            <%= button_tag(type: "submit", class: "btn btn-primary search-button") do %>
              <span class="glyphicon glyphicon-search"></span>
            <% end %>
          <% end %> 
        </div>  
      </div>
    </div>  
  </nav>
  <div class="container message-board">
    <% if notice %>
      <p id="notice" class="alert alert-info"><%= notice %></p>
    <% end %>
  </div>

  <%=yield %>

    <footer>
      <div id="login">
        <%if user_signed_in? %>
          <%=link_to( 'Logout', destroy_user_session_path, :method=> :delete) %>
            <span class="glyphicon glyphicon-log-out"></span>
            <% else %>
              <%=link_to( 'Login', new_user_session_path) %>
                <span class="glyphicon glyphicon-log-in"></span>
                <% end %>
      </div>
      &copy; Weepys Web Development 2017
    </footer>
</body>

</html>